# Generated by Django 5.0.4 on 2024-05-08 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='user_id',
            new_name='telegram_id',
        ),
    ]
